/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgmReportsRouteImport } from './routes/agm-reports'
import { Route as ArbitrationRouteImport } from './routes/arbitration'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BuildingRegulationsRouteImport } from './routes/building-regulations'
import { Route as BuildpressMagazineRouteImport } from './routes/buildpress-magazine'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CpdRapporteurReportsRouteImport } from './routes/cpd-rapporteur-reports'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as GeneralDownloadsRouteImport } from './routes/general-downloads'
import { Route as LiaisonCommitteesReportsRouteImport } from './routes/liaison-committees-reports'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MulikaMjengoReportRouteImport } from './routes/mulika-mjengo-report'
import { Route as OpinionEditorialsRouteImport } from './routes/opinion-editorials'
import { Route as PressStatementsRouteImport } from './routes/press-statements'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SalarySurveyRouteImport } from './routes/salary-survey'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusOfTheBuiltEnvironmentRouteImport } from './routes/status-of-the-built-environment'
import { Route as StoreRouteImport } from './routes/store'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as InitiativesSlugRouteImport } from './routes/initiatives.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgmReportsRoute = AgmReportsRouteImport.update({
  id: '/agm-reports',
  path: '/agm-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrationRoute = ArbitrationRouteImport.update({
  id: '/arbitration',
  path: '/arbitration',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRegulationsRoute = BuildingRegulationsRouteImport.update({
  id: '/building-regulations',
  path: '/building-regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildpressMagazineRoute = BuildpressMagazineRouteImport.update({
  id: '/buildpress-magazine',
  path: '/buildpress-magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRapporteurReportsRoute = CpdRapporteurReportsRouteImport.update({
  id: '/cpd-rapporteur-reports',
  path: '/cpd-rapporteur-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralDownloadsRoute = GeneralDownloadsRouteImport.update({
  id: '/general-downloads',
  path: '/general-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LiaisonCommitteesReportsRoute =
  LiaisonCommitteesReportsRouteImport.update({
    id: '/liaison-committees-reports',
    path: '/liaison-committees-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MulikaMjengoReportRoute = MulikaMjengoReportRouteImport.update({
  id: '/mulika-mjengo-report',
  path: '/mulika-mjengo-report',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionEditorialsRoute = OpinionEditorialsRouteImport.update({
  id: '/opinion-editorials',
  path: '/opinion-editorials',
  getParentRoute: () => rootRouteImport,
} as any)
const PressStatementsRoute = PressStatementsRouteImport.update({
  id: '/press-statements',
  path: '/press-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SalarySurveyRoute = SalarySurveyRouteImport.update({
  id: '/salary-survey',
  path: '/salary-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusOfTheBuiltEnvironmentRoute =
  StatusOfTheBuiltEnvironmentRouteImport.update({
    id: '/status-of-the-built-environment',
    path: '/status-of-the-built-environment',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesSlugRoute = InitiativesSlugRouteImport.update({
  id: '/initiatives/$slug',
  path: '/initiatives/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-reports': typeof AgmReportsRoute
  '/arbitration': typeof ArbitrationRoute
  '/awards': typeof AwardsRoute
  '/bills': typeof BillsRoute
  '/building-regulations': typeof BuildingRegulationsRoute
  '/buildpress-magazine': typeof BuildpressMagazineRoute
  '/contact': typeof ContactRoute
  '/cpd-rapporteur-reports': typeof CpdRapporteurReportsRoute
  '/csr': typeof CsrRoute
  '/general-downloads': typeof GeneralDownloadsRoute
  '/liaison-committees-reports': typeof LiaisonCommitteesReportsRoute
  '/membership': typeof MembershipRoute
  '/mulika-mjengo-report': typeof MulikaMjengoReportRoute
  '/opinion-editorials': typeof OpinionEditorialsRoute
  '/press-statements': typeof PressStatementsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/salary-survey': typeof SalarySurveyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status-of-the-built-environment': typeof StatusOfTheBuiltEnvironmentRoute
  '/store': typeof StoreRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-reports': typeof AgmReportsRoute
  '/arbitration': typeof ArbitrationRoute
  '/awards': typeof AwardsRoute
  '/bills': typeof BillsRoute
  '/building-regulations': typeof BuildingRegulationsRoute
  '/buildpress-magazine': typeof BuildpressMagazineRoute
  '/contact': typeof ContactRoute
  '/cpd-rapporteur-reports': typeof CpdRapporteurReportsRoute
  '/csr': typeof CsrRoute
  '/general-downloads': typeof GeneralDownloadsRoute
  '/liaison-committees-reports': typeof LiaisonCommitteesReportsRoute
  '/membership': typeof MembershipRoute
  '/mulika-mjengo-report': typeof MulikaMjengoReportRoute
  '/opinion-editorials': typeof OpinionEditorialsRoute
  '/press-statements': typeof PressStatementsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/salary-survey': typeof SalarySurveyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status-of-the-built-environment': typeof StatusOfTheBuiltEnvironmentRoute
  '/store': typeof StoreRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-reports': typeof AgmReportsRoute
  '/arbitration': typeof ArbitrationRoute
  '/awards': typeof AwardsRoute
  '/bills': typeof BillsRoute
  '/building-regulations': typeof BuildingRegulationsRoute
  '/buildpress-magazine': typeof BuildpressMagazineRoute
  '/contact': typeof ContactRoute
  '/cpd-rapporteur-reports': typeof CpdRapporteurReportsRoute
  '/csr': typeof CsrRoute
  '/general-downloads': typeof GeneralDownloadsRoute
  '/liaison-committees-reports': typeof LiaisonCommitteesReportsRoute
  '/membership': typeof MembershipRoute
  '/mulika-mjengo-report': typeof MulikaMjengoReportRoute
  '/opinion-editorials': typeof OpinionEditorialsRoute
  '/press-statements': typeof PressStatementsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/salary-survey': typeof SalarySurveyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status-of-the-built-environment': typeof StatusOfTheBuiltEnvironmentRoute
  '/store': typeof StoreRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agm-reports'
    | '/arbitration'
    | '/awards'
    | '/bills'
    | '/building-regulations'
    | '/buildpress-magazine'
    | '/contact'
    | '/cpd-rapporteur-reports'
    | '/csr'
    | '/general-downloads'
    | '/liaison-committees-reports'
    | '/membership'
    | '/mulika-mjengo-report'
    | '/opinion-editorials'
    | '/press-statements'
    | '/programs'
    | '/resources'
    | '/salary-survey'
    | '/sitemap.xml'
    | '/status-of-the-built-environment'
    | '/store'
    | '/students'
    | '/team'
    | '/chapters/$slug'
    | '/events/$slug'
    | '/initiatives/$slug'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agm-reports'
    | '/arbitration'
    | '/awards'
    | '/bills'
    | '/building-regulations'
    | '/buildpress-magazine'
    | '/contact'
    | '/cpd-rapporteur-reports'
    | '/csr'
    | '/general-downloads'
    | '/liaison-committees-reports'
    | '/membership'
    | '/mulika-mjengo-report'
    | '/opinion-editorials'
    | '/press-statements'
    | '/programs'
    | '/resources'
    | '/salary-survey'
    | '/sitemap.xml'
    | '/status-of-the-built-environment'
    | '/store'
    | '/students'
    | '/team'
    | '/chapters/$slug'
    | '/events/$slug'
    | '/initiatives/$slug'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agm-reports'
    | '/arbitration'
    | '/awards'
    | '/bills'
    | '/building-regulations'
    | '/buildpress-magazine'
    | '/contact'
    | '/cpd-rapporteur-reports'
    | '/csr'
    | '/general-downloads'
    | '/liaison-committees-reports'
    | '/membership'
    | '/mulika-mjengo-report'
    | '/opinion-editorials'
    | '/press-statements'
    | '/programs'
    | '/resources'
    | '/salary-survey'
    | '/sitemap.xml'
    | '/status-of-the-built-environment'
    | '/store'
    | '/students'
    | '/team'
    | '/chapters/$slug'
    | '/events/$slug'
    | '/initiatives/$slug'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgmReportsRoute: typeof AgmReportsRoute
  ArbitrationRoute: typeof ArbitrationRoute
  AwardsRoute: typeof AwardsRoute
  BillsRoute: typeof BillsRoute
  BuildingRegulationsRoute: typeof BuildingRegulationsRoute
  BuildpressMagazineRoute: typeof BuildpressMagazineRoute
  ContactRoute: typeof ContactRoute
  CpdRapporteurReportsRoute: typeof CpdRapporteurReportsRoute
  CsrRoute: typeof CsrRoute
  GeneralDownloadsRoute: typeof GeneralDownloadsRoute
  LiaisonCommitteesReportsRoute: typeof LiaisonCommitteesReportsRoute
  MembershipRoute: typeof MembershipRoute
  MulikaMjengoReportRoute: typeof MulikaMjengoReportRoute
  OpinionEditorialsRoute: typeof OpinionEditorialsRoute
  PressStatementsRoute: typeof PressStatementsRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  SalarySurveyRoute: typeof SalarySurveyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusOfTheBuiltEnvironmentRoute: typeof StatusOfTheBuiltEnvironmentRoute
  StoreRoute: typeof StoreRoute
  StudentsRoute: typeof StudentsRoute
  TeamRoute: typeof TeamRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  InitiativesSlugRoute: typeof InitiativesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agm-reports': {
      id: '/agm-reports'
      path: '/agm-reports'
      fullPath: '/agm-reports'
      preLoaderRoute: typeof AgmReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitration': {
      id: '/arbitration'
      path: '/arbitration'
      fullPath: '/arbitration'
      preLoaderRoute: typeof ArbitrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-regulations': {
      id: '/building-regulations'
      path: '/building-regulations'
      fullPath: '/building-regulations'
      preLoaderRoute: typeof BuildingRegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildpress-magazine': {
      id: '/buildpress-magazine'
      path: '/buildpress-magazine'
      fullPath: '/buildpress-magazine'
      preLoaderRoute: typeof BuildpressMagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd-rapporteur-reports': {
      id: '/cpd-rapporteur-reports'
      path: '/cpd-rapporteur-reports'
      fullPath: '/cpd-rapporteur-reports'
      preLoaderRoute: typeof CpdRapporteurReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-downloads': {
      id: '/general-downloads'
      path: '/general-downloads'
      fullPath: '/general-downloads'
      preLoaderRoute: typeof GeneralDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liaison-committees-reports': {
      id: '/liaison-committees-reports'
      path: '/liaison-committees-reports'
      fullPath: '/liaison-committees-reports'
      preLoaderRoute: typeof LiaisonCommitteesReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulika-mjengo-report': {
      id: '/mulika-mjengo-report'
      path: '/mulika-mjengo-report'
      fullPath: '/mulika-mjengo-report'
      preLoaderRoute: typeof MulikaMjengoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion-editorials': {
      id: '/opinion-editorials'
      path: '/opinion-editorials'
      fullPath: '/opinion-editorials'
      preLoaderRoute: typeof OpinionEditorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-statements': {
      id: '/press-statements'
      path: '/press-statements'
      fullPath: '/press-statements'
      preLoaderRoute: typeof PressStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-survey': {
      id: '/salary-survey'
      path: '/salary-survey'
      fullPath: '/salary-survey'
      preLoaderRoute: typeof SalarySurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-of-the-built-environment': {
      id: '/status-of-the-built-environment'
      path: '/status-of-the-built-environment'
      fullPath: '/status-of-the-built-environment'
      preLoaderRoute: typeof StatusOfTheBuiltEnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/$slug': {
      id: '/initiatives/$slug'
      path: '/initiatives/$slug'
      fullPath: '/initiatives/$slug'
      preLoaderRoute: typeof InitiativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgmReportsRoute: AgmReportsRoute,
  ArbitrationRoute: ArbitrationRoute,
  AwardsRoute: AwardsRoute,
  BillsRoute: BillsRoute,
  BuildingRegulationsRoute: BuildingRegulationsRoute,
  BuildpressMagazineRoute: BuildpressMagazineRoute,
  ContactRoute: ContactRoute,
  CpdRapporteurReportsRoute: CpdRapporteurReportsRoute,
  CsrRoute: CsrRoute,
  GeneralDownloadsRoute: GeneralDownloadsRoute,
  LiaisonCommitteesReportsRoute: LiaisonCommitteesReportsRoute,
  MembershipRoute: MembershipRoute,
  MulikaMjengoReportRoute: MulikaMjengoReportRoute,
  OpinionEditorialsRoute: OpinionEditorialsRoute,
  PressStatementsRoute: PressStatementsRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  SalarySurveyRoute: SalarySurveyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusOfTheBuiltEnvironmentRoute: StatusOfTheBuiltEnvironmentRoute,
  StoreRoute: StoreRoute,
  StudentsRoute: StudentsRoute,
  TeamRoute: TeamRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  InitiativesSlugRoute: InitiativesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
